name: taxcalc-dev
channels:
  - conda-forge
dependencies:
- python
- "numpy>=1.14"
- "pandas>=0.23"
- "bokeh>=0.13"
- requests
- numba
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- "paramtools>=0.10.0"
